name: quiz
description: Quizz app made by @bkaltug
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_native_splash: ^2.3.7
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/launcher_icon.png"

flutter_native_splash:
  color: "#800080 "
  android: true
  ios: true
  android_12:
    image: "assets/icons/launcher_icon.png"
    color: "#800080 "

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
